### ISSUE TITLE
Not working on Oneplus 8T / Android 12

### ISSUE THREAD

**Issue by Chrisplayer123** [reiryuki/Volume-Booster-Magisk-Module#2]
Sadly the module does nothing.
The Bluetooth volume output is very low because i have the EU Rom and i think this has some strange volume limiter.
How i can boost the volume?
V4a is installed but when i crank the bass up the limiter is too strong and the overall volume goes up and down.
The old OS was so much louder
I can't change the values by myself on mixer_paths.xml because system is read only 😐
Any ideas how i can solve it?
It is very annoying and frustrating!

**Comment by reiryuki** [comment]
Not following bug report protocol: https://t.me/androidryukimodsdiscussions/2618
